print(" Give Me Numbers. ")
Num1 = input(" Whats your first number?! ")
Num2 = input(" Whats The Second One? ")
Num1 = int(Num1)
Num2 = int(Num2)

print(str(Num1) + "+" + str(Num2) + "=" + str(Num1 + Num2))
print(str(Num1) + "-" + str(Num2) + "=" + str(Num1 - Num2))
print(str(Num1) + "*" + str(Num2) + "=" + str(Num1 * Num2))
print(str(Num1) + "/" + str(Num2) + "=" + str(Num1 / Num2))